### ISSUE TITLE
BARN Challenge Set Dynamic Obstacles

### ISSUE THREAD

**Issue by nfhe** [TempleRAIL/nav-competition-icra2022-drl-vo#2]
I'm delighted to see that the authors have open-sourced such excellent navigation algorithms. However, I'm currently facing some challenges and hope you can assist me. I can run Ubuntu 20.04 on Docker with the robot navigation training you provided. After training the model, it performs well in the static BARN environment. Now, I want to run it in the dynamic BARN environment, but I couldn't find any tutorials in your repository. 

If you could provide guidance on this matter, I would greatly appreciate it.

**Comment by zzuxzt** [comment]
Hi, thanks for your interest in our work. In this current repository, it sets the pedestrian kinematic maps to 0 values and works for the static BARN challenge. Since I am not familar with the details of the dynamic BARN challenge, I think you need to detect the dynamic obstacles first.You can then incorporate the detected kinematic information of dynamic obstacles into our pedestrian kinematic maps. The details of our DRL-VO control policy can be found in our paper ["DRL-VO: Learning to Navigate Through Crowded Dynamic Scenes Using Velocity Obstacles"](https://doi.org/10.1109/TRO.2023.3257549). Hope it helps you in some way.

**Comment by nfhe** [comment]
Thank you very much for your response to my question. Thank you for your patient response and guidance.
